/**
 * Google Gemini AI Integration
 */

const axios = require('axios');
const dotenv = require('dotenv');
dotenv.config();

const API_KEY = process.env.GEMINI_API_KEY;
const MODEL = process.env.GEMINI_MODEL || 'gemini-pro';

async function generateText(prompt) {
  if (!API_KEY) {
    throw new Error('GEMINI_API_KEY not configured in environment variables');
  }

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${API_KEY}`;

  const requestBody = {
    contents: [{
      parts: [{ text: prompt }]
    }],
    generationConfig: {
      temperature: 0.7,
      topK: 40,
      topP: 0.95,
      maxOutputTokens: 2048,
    }
  };

  try {
    const response = await axios.post(url, requestBody, {
      headers: {
        'Content-Type': 'application/json',
      },
      timeout: 30000
    });

    // Extract the text from the response
    const text = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!text) {
      console.error('Unexpected API response:', response.data);
      throw new Error('No text generated by Gemini AI');
    }

    return text;

  } catch (error) {
    console.error('Gemini API Error:');
    if (error.response) {
      console.error('Status:', error.response.status);
      console.error('Data:', error.response.data);
      
      if (error.response.status === 403) {
        throw new Error('Gemini API key is invalid or quota exceeded');
      } else if (error.response.status === 404) {
        throw new Error(`Gemini model '${MODEL}' not found. Try 'gemini-pro' or 'gemini-1.5-flash'`);
      } else {
        throw new Error(`Gemini API Error ${error.response.status}: ${error.response.data?.error?.message || 'Unknown error'}`);
      }
    } else if (error.request) {
      throw new Error('No response from Gemini API. Check your internet connection.');
    } else {
      throw new Error(`Failed to contact Gemini API: ${error.message}`);
    }
  }
}

module.exports = {
  generateText
};